import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { ExternalLink, Loader2, Globe, ArrowRight } from "lucide-react";

interface WebsitePreview {
  id: string;
  slug: string;
  website_type: string | null;
  target_audience: string | null;
  sections: { name: string; heading: string; content: string }[];
  created_at: string;
}

export default function Gallery() {
  const [websites, setWebsites] = useState<WebsitePreview[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchWebsites() {
      const { data, error } = await supabase
        .from("generated_websites")
        .select("id, slug, website_type, target_audience, sections, created_at")
        .order("created_at", { ascending: false })
        .limit(50);

      if (error) {
        console.error("Error fetching websites:", error);
      } else if (data) {
        const parsed = data.map((item) => ({
          ...item,
          sections: Array.isArray(item.sections) 
            ? (item.sections as WebsitePreview['sections'])
            : [],
        }));
        setWebsites(parsed);
      }
      setLoading(false);
    }

    fetchWebsites();
  }, []);

  const getHeroHeading = (sections: WebsitePreview['sections']) => {
    const hero = sections.find(s => s.name?.toLowerCase() === 'hero');
    return hero?.heading || sections[0]?.heading || "Untitled Website";
  };

  const getPreviewText = (sections: WebsitePreview['sections']) => {
    const hero = sections.find(s => s.name?.toLowerCase() === 'hero');
    const content = hero?.content || sections[0]?.content || "";
    return content.length > 120 ? content.substring(0, 120) + "..." : content;
  };

  return (
    <div className="min-h-screen bg-background">
      <Header tier="pro" requestsUsed={0} requestsLimit={20} />
      
      <main className="py-20">
        <div className="container mx-auto px-4">
          {/* Page header */}
          <div className="text-center mb-16">
            <h1 className="text-4xl font-bold mb-4 sm:text-5xl">
              Website <span className="gradient-text">Gallery</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Explore websites generated by the SiteForge AI community. Get inspired and see what's possible.
            </p>
          </div>

          {/* Loading state */}
          {loading && (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          )}

          {/* Empty state */}
          {!loading && websites.length === 0 && (
            <div className="text-center py-20">
              <Globe className="h-16 w-16 mx-auto text-muted-foreground/50 mb-4" />
              <h2 className="text-xl font-semibold mb-2">No websites yet</h2>
              <p className="text-muted-foreground mb-6">
                Be the first to generate and share a website!
              </p>
              <Link to="/">
                <Button variant="gradient" className="relative z-10">
                  <span className="relative z-10 flex items-center gap-2">
                    Create Website
                    <ArrowRight className="h-4 w-4" />
                  </span>
                </Button>
              </Link>
            </div>
          )}

          {/* Website grid */}
          {!loading && websites.length > 0 && (
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {websites.map((website, index) => (
                <Link
                  key={website.id}
                  to={`/site/${website.slug}`}
                  className="group glass-card p-6 transition-all hover:border-primary/50 hover:shadow-elegant animate-fade-in"
                  style={{ animationDelay: `${index * 50}ms` }}
                >
                  {/* Card header */}
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-2">
                      <div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Globe className="h-4 w-4 text-primary" />
                      </div>
                      <span className="text-xs font-medium text-muted-foreground">
                        {website.website_type || "Website"}
                      </span>
                    </div>
                    <ExternalLink className="h-4 w-4 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />
                  </div>

                  {/* Card content */}
                  <h3 className="font-semibold text-lg mb-2 line-clamp-2 group-hover:text-primary transition-colors">
                    {getHeroHeading(website.sections)}
                  </h3>
                  <p className="text-sm text-muted-foreground line-clamp-3 mb-4">
                    {getPreviewText(website.sections)}
                  </p>

                  {/* Card footer */}
                  <div className="flex items-center justify-between text-xs text-muted-foreground">
                    <span>{website.sections.length} sections</span>
                    <span>{new Date(website.created_at).toLocaleDateString()}</span>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}
